### ISSUE TITLE
Mac Issue - Using pyenv

### ISSUE THREAD

**Issue by casbu** [junebug12851/Sims4ScriptingBPProj#1]
Hello! Using Mac with PyCharm (Community). 
I attempted to decompile and received a zero division error in decompile_print_totals. 
I am using pyenv and installed uncompyle6 into version 3.7.6 (3.7.9 is not available using pyenv, but I don't believe that should matter).
Is there something I missed? I seem to have set up my path files correctly...perhaps not. Can you take a look?

<img width="1065" alt="Screen Shot 2020-10-25 at 1 24 48 PM" src="https://user-images.githubusercontent.com/52548057/97116819-77404080-16c5-11eb-80fb-1ae063f8a41e.png">

**Comment by junebug12851** [comment]
Thank you very much for reporting this, I'm about to make an update that will cleanup this error making it shorter and more informative.

When the script went to begin decompilation, it found nothing to decompile. This error message happened because I didn't prepare the script for that scenario.

Based on your screenshot above, do these paths exist on your computer

* ~/Applications/The Sims 4/Data/Simulation/Gameplay
* ~/Applications/The Sims 4/Game/Bin/Python

Lets start there and we can proceed onward if they do exist

**Comment by casbu** [comment]
Thank for your prompt reply, this makes sense now. 

The Sims 4/Game path does not exist. The only files there are Client, Shared, and Simulation.

**Comment by junebug12851** [comment]
Interesting

* Does `~/Applications/The Sims 4/Contents/Python/` contain `generated.zip` and
* Does `~/Applications/The Sims 4/Contents/Data/Simulation/Gameplay` contain `base.zip`, `core.zip` and `simulation.zip`?

If it does then those are the folders that should be used on mac

**Comment by casbu** [comment]
Yes, that is exactly correct!

**Comment by casbu** [comment]
Could I just modify the Data and Game Folders file paths at the bottom of settings.py to 
`os.path.join(game_folder, 'Python')` instead of `game_folder, 'Game', 'Bin', 'Python'` ?

**Comment by junebug12851** [comment]
This is good news for you then and bad news for me lol

Right now here's how you can correct it:

1. Open `settings.py`
2. Look near the very end, you should see 2 entries named `gameplay_folder_data` and `gameplay_folder_game`. What these refer to is the location of those correct folders inside the game folder which are wrong on Mac because I'm convinced EA secretly likes to make thing very difficult on purpose.
3. Change `gameplay_folder_data` to `os.path.join(game_folder, 'Contents', 'Data', 'Simulation', 'Gameplay')`
4. Change `gameplay_folder_game` to `os.path.join(game_folder, 'Contents', 'Python')`

As for me, I now have to figure out how to make for 2 different paths on each system. Let me know if this helps you.

**Comment by casbu** [comment]
Thank you so much June! I will let you know if I run into any trouble or not. The Sims Team really DOES like to make it particularly difficult to do literally anything-at-all. I appreciate your help. I'll get back to you in a moment.

**Comment by casbu** [comment]
Weird. It did not fix the problem and I am receiving the same error. *sigh* They must really not want us to mess with their game. I imagine I will run into the same problem again but I want to make sure it wasn't anything on my end. Ill download `python 3.7` and not use `pyenv` and see if there was an issue with the `uncompyle6`.

**Comment by junebug12851** [comment]
Can you take a screenshot of the end of the settings file? It's really strange you're still having this issue, I hate I don't have a mac to test it myself.

**Comment by casbu** [comment]
No problem! I am more than happy to give as much detail as I can for you. Covid has confined me to my computer.

<img width="847" alt="Screen Shot 2020-10-25 at 4 04 25 PM" src="https://user-images.githubusercontent.com/52548057/97120308-c2fde480-16db-11eb-9315-b5dd38bcba48.png">

I also reset everything and still received the same message. I will attempt to debug and see what it says. At one point I got a traceback base object exception but I didn't record it before I reset everything. I don't know if that means anything to you but I'll try to recreate it. I'm not well-versed in using debug ha but if it will help, you can walk me through it and I can provide whatever you need.

**Comment by casbu** [comment]
<img width="1262" alt="Screen Shot 2020-10-25 at 4 26 28 PM" src="https://user-images.githubusercontent.com/52548057/97120728-d6f71580-16de-11eb-85e7-84d8d6983402.png">

**Comment by junebug12851** [comment]
Does your game folder still point to `~/Applications/The Sims 4` or did you change it to `~/Applications/The Sims 4/Contents`. It should be the former and still point to `~/Applications/The Sims 4`. I say this because it looks like at one point in the messages you thought of changing it.

**Comment by casbu** [comment]
I left the top the same otherwise it would attempt to find another Contents folder inside of the Contents folder. That's why I don't understand why it didn't work. Is there another method of file pathing I should use at the top of settings? I figured it was a requirement for Mac to use the os.path.join but I could be wrong...

<img width="836" alt="Screen Shot 2020-10-25 at 4 36 09 PM" src="https://user-images.githubusercontent.com/52548057/97120907-3144a600-16e0-11eb-8c33-c7057c628d47.png">

**Comment by junebug12851** [comment]
`os.path.join` is supposed to make paths work on all operating systems. Is it the exact same error in the exact same place?

**Comment by casbu** [comment]
Yes it is exactly the same. I also tried `'Users', 'casbu', ...` and received the same message. I thought expanduser took care of that. 
<img width="718" alt="Screen Shot 2020-10-25 at 4 48 40 PM" src="https://user-images.githubusercontent.com/52548057/97121184-f0e62780-16e1-11eb-9799-b9d1123db0de.png">

<img width="1072" alt="Screen Shot 2020-10-25 at 4 42 03 PM" src="https://user-images.githubusercontent.com/52548057/97121004-060e8680-16e1-11eb-9c83-29b879a91d92.png">

**Comment by junebug12851** [comment]
Go head and replace the contents of `Utility/helpers_decompile.py` with the update I made, you should still get an error but it should hopefully be more informative and less messy https://github.com/junebug12851/Sims4ScriptingBPProj/blob/master/Utility/helpers_decompile.py

Can you confirm after doing so the red text goes away in place of a proper error message? In the meantime I'm still trying to figure this out, I thank you for being patient and I'm sorry this is causing so much trouble.

**Comment by casbu** [comment]
It's not a problem at all, I appreciate you taking the time to go through this with me. Very cool of you. Let me update and I'll be back with you shortly.

**Comment by casbu** [comment]
Progress. It's definitely the file path. I'm just not sure why it is incorrect.

<img width="718" alt="Screen Shot 2020-10-25 at 5 01 25 PM" src="https://user-images.githubusercontent.com/52548057/97121432-d01ed180-16e3-11eb-8d53-a65fcb7173ce.png">

**Comment by casbu** [comment]
Interesting. Changing the above settings to my User and Name created a User folder in my project folder. I didn't unpack anything inside the Python folder but the fact that it is there is weird.

<img width="1089" alt="Screen Shot 2020-10-25 at 5 10 55 PM" src="https://user-images.githubusercontent.com/52548057/97121595-0c9efd00-16e5-11eb-86ca-345a7ecea12d.png">

**Comment by junebug12851** [comment]
It's good the red error messages were cleaned up

Ahhh, wait! Your screenshot gave me an idea.

Delete the folder you just mentioned inside your project folder and replace `Users` with `/Users`. See if that helps.

**Comment by casbu** [comment]
Deleted it. Ran decompiler. No luck. It did however put the `--util` folder back into my main projects folder.

**Comment by junebug12851** [comment]
When you say put the `__util` folder back into your main projects folder, you mean as normal like `Sims 4 Projects/__util` or `Sims 4 Projects/Project Name/__util`?

**Comment by casbu** [comment]
Yes, it's back in the original Sims 4 Projects folder that holds my actual mod project folder.

**Comment by junebug12851** [comment]
In `helpers/helpers_decompile.py`, the function `def decompile_zips(src_dir: str, dst_dir: str) -> None:` on line `175`

Can you add 2 print statements like so

```py
...
    print(src_dir)
    for root, dirs, files in os.walk(src_dir):
        for ext_filter in script_package_types:
            for filename in fnmatch.filter(files, ext_filter):
                print(filename)
                decompile_zip(root, filename, dst_dir)
```

and tell me what it outputs

**Comment by ssinakhot** [comment]
Hey guys, 
Just an fyi, the proper path to the Contents folder needs to be `/Users/user/Applications/The Sims 4.app/Contents`
Without the `.app` any of the paths you try to use won't work. So technically `~/Applications/The Sims 4.app/Contents` should work as well.

**Comment by casbu** [comment]
I only have `helpers_decompile.py` under Utility. Should it be under the helper folder?? I still ran the function and it printed:

```
/Users/casbu/Applications/The Sims 4/Contents/Data/Simulation/Gameplay
/Users/casbu/Applications/The Sims 4/Contents/Python
```

**Comment by junebug12851** [comment]
Your correct `Utility/helpers_decompile.py`

I really don't understand whats going on. If you go to `/Users/casbu/Applications/The Sims 4/Contents/Data/Simulation/Gameplay` in Finder, you do see `zip` files? Or are they different extensions like `tar.gz` or something else?

**Comment by ssinakhot** [comment]
Also, I believe in the finder you won't see the words `.app` but you should be able to see it if you browse to it via terminal. I don't have Sims 4 installed on my Macbook anymore to verify. Good luck! Hope this helps you guys.

**Comment by casbu** [comment]
All three are zip files. I'm at a loss as to what's wrong.

**Comment by casbu** [comment]
Oh my gosh! ssinakhot thank you! Let me try this.

**Comment by junebug12851** [comment]
Thank you @ssinakhot !!!

**Comment by ssinakhot** [comment]
No! Thank you @junebug12851 for packaging together an interesting boilerplate to simplify the the scripting portion of Sims 4. 

I love how you added in the devmode/debugging capabilities. I will be testing them out on my Intellij IDEA version. The code is pretty well commented to help anyone getting into python. I am sure people will be using and contributing to the project to help keep it up to date.

I just wish the repo name wasn't "Sims4ScriptingBPProj". Haha!

**Comment by casbu** [comment]
Well I could cry...it did not work. 
<img width="1135" alt="Screen Shot 2020-10-25 at 5 46 40 PM" src="https://user-images.githubusercontent.com/52548057/97122242-124b1180-16ea-11eb-9eac-633e94782978.png">

I tried both ways:
```
os.path.join('Users', 'user', 'casbu', 'Applications', 'The Sims 4.app')
os.path.join('/Users', 'user', 'casbu', 'Applications', 'The Sims 4.app')
```

Did I mess this up? Should I include Contents and remove the 'Contents' part at the bottom of settings.py?

**Comment by junebug12851** [comment]
@ssinakhot Thank you for the great feedback!!! Also I agree about the project name, I should have spent more time on it but it's named what it is now lol.

**Comment by ssinakhot** [comment]
Just slight typo there buddy:

Try this

`os.path.join('/Users', 'casbu', 'Applications', 'The Sims 4.app')`
or
`os.path.join('~','casbu', 'Applications', 'The Sims 4.app')`

See if one of those works.

**Comment by ssinakhot** [comment]
@junebug12851  You can rename repositories. But you'd need to update all your posts and references you had before. 

I forked your project and renamed it to `sims4_mod_boilerplate` so it's nicely named in my local drive.

**Comment by casbu** [comment]
Ok I adjusted accordingly and received this message:

<img width="1135" alt="Screen Shot 2020-10-25 at 5 54 26 PM" src="https://user-images.githubusercontent.com/52548057/97122392-20e5f880-16eb-11eb-801f-6b9fc1c7cf1f.png">

**Comment by junebug12851** [comment]
I'm looking into this still but this means it was ready to begin decompiling and has a `pyc` file ready to decompile, however when it went to execute `uncompyle6` it wasn't able to find it at all. This means we're making progress and now we're at a different issue. Congrats on solving the first issue!

So to fix the second issue, go to your Python folder and in `Scripts` look for a file called `uncompyle6`, do you see it?

**Comment by casbu** [comment]
Hm there is a problem. Mac does not create a Scripts folder. It's just in there when I pip'd it in. 
<img width="1135" alt="Screen Shot 2020-10-25 at 6 06 29 PM" src="https://user-images.githubusercontent.com/52548057/97122617-d06f9a80-16ec-11eb-9ced-13ea573a462a.png">

When I used debug it shows this. Could this be why?
<img width="852" alt="Screen Shot 2020-10-25 at 6 07 40 PM" src="https://user-images.githubusercontent.com/52548057/97122644-fac15800-16ec-11eb-90ad-3f8f9d288091.png">

Not even sure if the above matters as long as I can access the file. But I am able to locate the file, yes.

**Comment by junebug12851** [comment]
This would be the reason why, I suspected it was different on mac as well.

Can you give me the absolute path on your machine to `uncompyle6`.

**Comment by casbu** [comment]
`Macintosh HD/Users/casbu/.pyenv/versions/3.7.6/bin/uncompyle6`

**Comment by junebug12851** [comment]
So try this

In `Utility/helpers_package.py`, replace the imports at the top with this:

```py
import os
from subprocess import run, PIPE, call, DEVNULL
from Utility.helpers_path import get_sys_path, get_sys_scripts_folder, get_full_filepath, get_sys_folder
```

and somehwere around line 41 or near the bottom replace these lines in `exec_package` with this

```py
    cmd = os.path.join(get_sys_folder(), 'bin', package)
    result = run(cmd + " " + args, capture_output=True, text=True)
    return (not str(result.stderr)) and (result.returncode == 0)
```

See if that works. We're close to the end!

**Comment by casbu** [comment]
<img width="1257" alt="Screen Shot 2020-10-25 at 6 34 32 PM" src="https://user-images.githubusercontent.com/52548057/97123287-bafc6f80-16f0-11eb-9fc2-55221edd31ce.png">

**Comment by junebug12851** [comment]
Did you make those changes in `helpers_package.py` or `helpers_path.py`?

**Comment by casbu** [comment]
Whoops! Okay I fixed it. Sorry about that.

<img width="1257" alt="Screen Shot 2020-10-25 at 6 42 04 PM" src="https://user-images.githubusercontent.com/52548057/97123507-c8fec000-16f1-11eb-8413-777d1857c2b2.png">

**Comment by junebug12851** [comment]
It's not a problem, did you add 

```py
import os
from subprocess import run, PIPE, call, DEVNULL
from Utility.helpers_path import get_sys_path, get_sys_scripts_folder, get_full_filepath, get_sys_folder
```

at the top of the same file `helpers_package.py`?

**Comment by casbu** [comment]
Gosh I am out of it. I missed the `get_sys_folder`. Here are new results.

<img width="1273" alt="Screen Shot 2020-10-25 at 6 51 30 PM" src="https://user-images.githubusercontent.com/52548057/97123808-1a5b7f00-16f3-11eb-8aeb-76a58644fb57.png">

**Comment by junebug12851** [comment]
It's no problem and this is really excellent! I feel we're almost there.

In `helpers_package.py` in `def exec_package` change this from:

```py
cmd = os.path.join(get_sys_folder(), 'bin', package)
```

to

```py
cmd = os.path.join(get_sys_folder(), package)
```

I think this may be it!

**Comment by casbu** [comment]
Eek! I hope so. 

<img width="988" alt="Screen Shot 2020-10-25 at 6 59 33 PM" src="https://user-images.githubusercontent.com/52548057/97124059-3a3f7280-16f4-11eb-95f4-953ae93686ec.png">

**Comment by junebug12851** [comment]
But the file does exist doesn't it?

Can you visit `/Users/casbu/.pyenv/versions/3.7.6/bin/uncompyle6`? That should be the direct path to it.

**Comment by casbu** [comment]
It does! I don't understand! Does this look right?

<img width="988" alt="Screen Shot 2020-10-25 at 7 04 20 PM" src="https://user-images.githubusercontent.com/52548057/97124243-f0a35780-16f4-11eb-8718-e40363362013.png">

**Comment by casbu** [comment]
<img width="1299" alt="Screen Shot 2020-10-25 at 7 07 20 PM" src="https://user-images.githubusercontent.com/52548057/97124350-58f23900-16f5-11eb-913d-beeaf061ae4b.png">

**Comment by junebug12851** [comment]
Hmm, can you add 2 print statements after the `cmd` like so:

```py
...
    cmd = os.path.join(get_sys_folder(), 'bin', package)
    print(cmd)
    print(cmd + " " + args)
...
```

and tell me what it says. I'm really running out of ideas at this point

**Comment by casbu** [comment]
I tried the command with 'bin' included and one without since you had me change it previously. Both resulted in the same error:

`get_sys_folder(), 'bin', package)`
`get_sys_folder(), package)`

<img width="1051" alt="Screen Shot 2020-10-25 at 7 21 34 PM" src="https://user-images.githubusercontent.com/52548057/97124831-4d077680-16f7-11eb-87ef-15d7d74d1773.png">


Honestly, at this point that's okay. You have been working on this with me for the past 5 hours and I don't know how I can ever thank you enough for trying to resolve this. Do you have a patreon or anything?

**Comment by ssinakhot** [comment]
Your issue might be because of how you are using subprocess.run() and how MacOS parses commands.

You can try to place the cmd + args inside a list and see if that helps. 
so 
subprocess.run([path, arg1, arg2, arg3]) rather than trying to concat a string together.

**Comment by junebug12851** [comment]
I hope we can resolve it in the future and I'm sorry we couldn't figure it out and that it took so long. As for patreon, I don't but I've been meaning to set one up, currently I take donations through PayPal junehanabi@gmail.com.

Thank you for sticking with me!

**Comment by casbu** [comment]
Maybe it just won't work with pyenv and I'll have to install the python version directly in my system or something. Which is unfortunate but I don't mind the hassle if I can actually look at Sims python scripts to get some semblance of an idea of what I can do with it. Have a good evening...or morning/afternoon! You have been awesome. If you think of anything later on I've made sure to watch this repository. Go take a break ;)

**Comment by junebug12851** [comment]
@ssinakhot I really need to make a lot of upgrades in general on the code, especially to handle Mac now that I know more about Python and Sims 4 on Mac. If casbu tries it I hope it works. When all this is over I'm going to make some large-scale refactoring to the codebase.

@casbu Pyenv shouldn't really matter because in the end it's a working python installation in a folder of your computer. I may have to take that break lol. Try what ssinakhot said which is to replace

this

```py
result = run(cmd + " " + args, capture_output=True, text=True)
```

with this

```py
result = run([cmd, args], capture_output=True, text=True)
```

Good luck, I'm going to take a short break

**Comment by casbu** [comment]
@ssinakhot !!!!! That soothing wall of text that follows upon execution is a beautiful thing. I don't even know what to say. I really appreciate you. Wow. 

@junebug12851 fyi, I did not include 'bin' in the `exec_package` since it was creating a bin/bin/ situation. Just so you know! You both are awesome!

**Comment by casbu** [comment]
![image](https://user-images.githubusercontent.com/52548057/97126269-00726a00-16fc-11eb-950a-c68e141fca82.gif)

**Comment by junebug12851** [comment]
Wait, you got it working! That's really awesome! What did you do to get it working?

**Comment by casbu** [comment]
I kept the modifications we made to helpers_package and settings,  but removed the 'bin' under exec_package cmd, then did exactly what @ssinakhot  said about using a list instead of concat for sub_processes and it worked like a charm. Thank you both for all of your help tonight. Have a good one!

**Comment by casbu** [comment]
Darn. So it ran. I assumed it was working. It created all of the folders inside of base.zip, core.zip, etc so the process was able to locate the files. Unfortunately the conversion of all files failed. Can you think of a reason as to why?

<img width="1051" alt="Screen Shot 2020-10-26 at 9 06 36 AM" src="https://user-images.githubusercontent.com/52548057/97189764-904efd00-176a-11eb-833e-437a39e6f528.png">

**Comment by junebug12851** [comment]
Can you copy and paste in here just those last 2 lines, what I'm seeing is this

```
/Users/casbu/.pyenv/versions/3/7/6/bin/uncompyle6
/Users/casbu/.pyenv/versions/3/7/6/bin/uncompyle6 -o "/Users/casbu/Documents/Sims 4 Projects/__util/Python/generated/protocolbu....
```

If I could have the rest of that line

**Comment by casbu** [comment]
```
x/Users/casbu/.pyenv/versions/3.7.6/bin/uncompyle6
/Users/casbu/.pyenv/versions/3.7.6/bin/uncompyle6 -o "/Users/casbu/Documents/Sims 4 Projects/__util/Python/generated/protocolbuffers/RestApi_pb2.py" "/var/folders/w0/3ztzrskj41bcv36vjrtd239h0000gn/T/tmpcau9f1pf/protocolbuffers/RestApi_pb2.pyc"
x
```

**Comment by junebug12851** [comment]
It's feeding information to uncompyle6 correctly and the paramaters should be the same. If you type in `uncompyle6 --help`

you should see a line that's says this

```
uncompyle6 [OPTIONS]... [ FILE | DIR]...
```

Is it different on a mac?

**Comment by casbu** [comment]
It should be...but this is what I got.
<img width="502" alt="Screen Shot 2020-10-26 at 9 37 42 AM" src="https://user-images.githubusercontent.com/52548057/97193701-e6be3a80-176e-11eb-9976-e3fcdf41ca10.png">

**Comment by junebug12851** [comment]
That would be related to `pyenv`, could you run `/Users/casbu/.pyenv/versions/3.7.6/bin/uncompyle6 --help`?

**Comment by casbu** [comment]
let me try a few different ways, one moment.

**Comment by casbu** [comment]
Gotcha. Sorry. I am in the help menu now

**Comment by casbu** [comment]
Should I try decompyle3? I was looking at that in the uncompyle6 doc that it might work better.

**Comment by junebug12851** [comment]
@ssinakhot  and I are discussing using multiple compilers in a sequence for each file so that if one fails the other may succeed https://github.com/junebug12851/Sims4ScriptingBPProj/issues/2

However until then it should still work regardless, we have a different issue here where it's being told correctly what to do but it's not doing anything and returning an error.

Wait, lets see that error, give me a quick moment.

**Comment by junebug12851** [comment]
In `helpers_package.py` near the end, find `def exec_package(package: str, args: str) -> bool:` and add a print statement like so

```py
...
    result = run(cmd + " " + args, capture_output=True, text=True)
    print(result.stderr)
    return (not str(result.stderr)) and (result.returncode == 0)
```

hopefully it'll give us an indication as to whats going on

**Comment by casbu** [comment]
Yea I was afraid to replace the work we did so it's just taking a moment to surf through all the files. Should have results in a minute or so.

**Comment by casbu** [comment]
Noticing it is feeding back `No input files given to decompile`

<img width="878" alt="Screen Shot 2020-10-26 at 10 16 37 AM" src="https://user-images.githubusercontent.com/52548057/97198382-57b42100-1774-11eb-9092-3e07e4f7bd13.png">

**Comment by ssinakhot** [comment]
So uh, Just looking at the output I'm wondering why I see the `x` infront of the path for uncompyle6? Is that intentional?

**Comment by casbu** [comment]
Hm... I thought it was something you had included in the code to separate files? Guess not ha. I am not sure what that means.

**Comment by junebug12851** [comment]
The `x` is part of the progress bar. The progress bar is being broken up intil multiple lines because we have 3 print statement happening in that one function.

**Comment by ssinakhot** [comment]
It's okay, I'm pretty sure this is related to the arguments.

[cmd, args] => ["uncompyle6", "-o input1 input2"], this won't work for MacOS.

It needs to be ["uncompyle6", "-o", "input1", "input2"] for it to work.
 
I am working right now I might be able to spend a couple minutes fixing the code later tonight or you can do some refactor for that input type.

**Comment by junebug12851** [comment]
I'm working on a solution that involves that now. Give me a quick moment @casbu

**Comment by casbu** [comment]
Take your time, no rush.

**Comment by junebug12851** [comment]
The thing is I already tried this on Windows and I couldn't get it to work because of errors which is why I instead built a string but it may work for you. It requires making lots of changes though.

Make `exec_package` header look like this
```py
def exec_package(package: str, *args) -> bool:
```

Then, inside of the function, make run look like this

```py
result = run([cmd] + list(args), capture_output=True, text=True)
```

Then inside of `helpers_decompile.py ` you should see near line 96 `success = exec_package("uncompyle6",...`, make it look like this:

```py
            # Decompile it to destination
            success = exec_package("uncompyle6",
                                   "-o",
                                   '"' + dest_file_path + '"',
                                   '"' + src_file_path + '"')
```

This may or may not work for you, it gives errors on my end saying the file doesn't exist.

**Comment by casbu** [comment]
<img width="1038" alt="Screen Shot 2020-10-26 at 10 46 44 AM" src="https://user-images.githubusercontent.com/52548057/97201921-98ae3480-1778-11eb-82a7-0b917b893979.png">

**Comment by junebug12851** [comment]
Your exec_package.py should look like this

```py
def exec_package(package: str, *args) -> bool:
    """
    Executes the cli version of an installed python package

    :param package: Package name to execute
    :param args: Arguments to provide to the package
    :return: Return code for failure or success
    """

    cmd = get_full_filepath(get_sys_folder(), package)
    result = run([cmd] + list(args), capture_output=True, text=True)
    print(result.stderr)
    return (not str(result.stderr)) and (result.returncode == 0)
```

**Comment by casbu** [comment]
Woops let me remove the print on 52

**Comment by junebug12851** [comment]
Ah wait, it should look like this

```py
def exec_package(package: str, *args) -> bool:
    """
    Executes the cli version of an installed python package

    :param package: Package name to execute
    :param args: Arguments to provide to the package
    :return: Return code for failure or success
    """

    cmd = os.path.join(get_sys_folder(), package)
    result = run([cmd] + list(args), capture_output=True, text=True)
    print(result.stderr)
    return (not str(result.stderr)) and (result.returncode == 0)
```

An additional change I forgot because you're on a mac

**Comment by casbu** [comment]
Ok that didn't work but I put the os.path.join back. and now its stating these results:
<img width="1038" alt="Screen Shot 2020-10-26 at 10 52 49 AM" src="https://user-images.githubusercontent.com/52548057/97202552-651fda00-1779-11eb-829a-79d72dc78ac3.png">

**Comment by junebug12851** [comment]
That's the error I get which is why I didn't initially do what @ssinakhot suggested, perhaps I'm implementing it wrong.

**Comment by casbu** [comment]
Ooookay I'm getting a parse error, assertion error,  and its quite long.

<img width="1038" alt="Screen Shot 2020-10-26 at 10 56 58 AM" src="https://user-images.githubusercontent.com/52548057/97203021-f98a3c80-1779-11eb-973e-e67a8469953f.png">

**Comment by casbu** [comment]
Wait....it just worked??

<img width="1038" alt="Screen Shot 2020-10-26 at 10 57 59 AM" src="https://user-images.githubusercontent.com/52548057/97203195-1fafdc80-177a-11eb-99a9-ac1f193e5211.png">

**Comment by junebug12851** [comment]
Ahh, stop it and remove the print statements

**Comment by casbu** [comment]
Oh my gosh I think it's working!! Should there be a mini progress bar running?

**Comment by junebug12851** [comment]
There should be, that's what the dots and x's are for. I reccomend to stop it and remove the print statements so it looks like this 
![image](https://user-images.githubusercontent.com/1305564/97203606-6eb23d80-178b-11eb-9754-0500345162cc.png)

**Comment by junebug12851** [comment]
Looks like it's working!!!!!

**Comment by casbu** [comment]
Lifesaver!!!! <3 Thank you so much!

**Comment by junebug12851** [comment]
Your welcome!! Enjoy your decompiled files!

**Comment by casbu** [comment]
I shall!
