### ISSUE TITLE
Suggestion: Allow the option to specify a different decompiler

### ISSUE THREAD

**Issue by ssinakhot** [junebug12851/Sims4ScriptingBPProj#2]
Even though you are using a newer decompiler, having the option to switch to a different decompiler via settings would be beneficial. 

I tried out `uncompyle6` and compared it to the results from `unpyc37` and I have found that some of the files decompile better in `unpyc37`. 

In `client.py` for instance didn't get decompiled properly in the function `_get_stack_items_from_drag_object` on my end.

Right now, I'll be using your boilerplate but I made a quick modification to use `decompiler3` and `unpyc37` just to be able to compare the results. Since you may do some refactor, I just wanted to point this out in case you wanted to add a setting to specify exactly what decompiler program to use. 

Other decompilers that people could try:

https://fogity.wordpress.com/tools/python-decompiler/
https://github.com/andrew-tavera/unpyc37

**Comment by junebug12851** [comment]
I think that's a great idea, what do you think about it leveraging all 3 decompilers in order of succession if a file fails to decompile?

**Comment by ssinakhot** [comment]
I think that is an interesting idea. It not a bad idea to switch between the decompilers.

I am switching between the decompilers to see which gives the results I like more. Notice that decompyle3 ends up being a lot faster than the uncompyle6. The developer for uncompyle6 is working on decompyle3 which is apparently a re-write for python 3.7+.

I have a feeling that the order of decompilers that should be use should be `unpyc37` => `decompyle3` => `uncompyle6`. The reason I believe `unpyc37` might work better would be simply because the same developer that works on `unpyc37` is also the same developer for The Sims 4 Studio.

Here are my current results:

decompyle3 Results:
S: 2515 [96.07%], F: 103 [3.93%], T: 2618, 0:28

uncompyle6 Results:
S: 2469 [94.31%], F: 149 [5.69%], T: 2618, 0:54

https://github.com/rocky/python-decompile3
https://github.com/rocky/python-uncompyle6
https://github.com/andrew-tavera/unpyc37
https://fogity.wordpress.com/tools/python-decompiler/

I'll test out unpyc37 to see the results and post back.

**Comment by junebug12851** [comment]
Those are interesting results, I need to make a system that will try the files in that order. If anything can improve the speed that would be great and with this idea the speed and accuracy could be improved.

**Comment by ssinakhot** [comment]
unpyc37 Results:
S: 2535 [96.83%], F: 83 [3.17%], T: 2618, 0:00

decompyle3 Results:
S: 2515 [96.07%], F: 103 [3.93%], T: 2618, 0:28

uncompyle6 Results:
S: 2469 [94.31%], F: 149 [5.69%], T: 2618, 0:54

In terms of numbers of files and speed, unpyc37 is definitely on top. I can do a pull request for the changes I made to get `unpyc37` to work. I setup a submodule so you may not like that reference. 

I have not tried fogity's decompiler however, for what I need to be decompiled, Andrew's work is usable for me.

**Comment by junebug12851** [comment]
I don't mind pull requests but as much as submodules are useful I find they cause a ton of problems and complications. What's the submodule to?

**Comment by junebug12851** [comment]
These numbers looks really good, thank you for working on this.

**Comment by ssinakhot** [comment]
I added in andrew's unpyc3 as a submodule. I'll do a pull request and if you want I can drop the unpyc37 as a submodule and commit it directly to the project with license information and credit as well.

I found submodule useful in terms of just maintain the reference to whom they were developed by.

**Comment by junebug12851** [comment]
I agree about submodules having a lot of use, we can give them a try. The only other issue I can think of is making it complicated for modders who want to use the project but don't know anything about git which is the majority. I don't think Github includes submodules in zip downloads. If we continue with submodules then we'd need to setup a free Travis automated build so that Travis can auto-deploy all commits to Github Releases allowing users to download it from there with the submodules included.

**Comment by junebug12851** [comment]
Go ahead with the pull request and thank you again for the help

**Comment by junebug12851** [comment]
I merged the changes into a `dev` branch until I can setup the Travis project for auto-deployment so that users can continue to follow the old instructions and download the zip file. When Travis is setup I can merge dev to master and then update the instructions for people to follow who don't know how to use git.

**Comment by polyjitter** [comment]
I realize this is a closed issues, so apologies for necro'ing, but I did want to give a heads=up that using @junebug12851's suggestion of using multiple decompilers, it does appear I was able to receive a fully decompiled core and simulation.

I am sure you could get a full base, but it seems most of everything in base is actually just all base CPython libs so maybe it would be better to determine the versions in use by Sims 4 and just download the original libraries directly?
