### ISSUE TITLE
[not a bug] Could you make a custom aspiration or trait tutorial?

### ISSUE THREAD

**Issue by sdozier** [junebug12851/Sims4ScriptingBPProj#4]
Hi there,
Sorry, I'm not sure how else to get in touch with you! I loved your Medium Sims 4 tutorials and I saw it said to check in periodically for a part 7. I don't know if you already have a topic in mind, but I think a custom aspiration or trait would be popular. There's barely any material out there other than how to use Zerbu's tool, and I don't think it includes scripting.

I agree with a lot of your comments about Sims 4 modding being unsupported lol... thanks for your helpful tutorials :)

**Comment by junebug12851** [comment]
This project has been abandoned and so has the tutorial series. I've updated the README about the reason why. I'm very sorry to give the bad news.
