### ISSUE TITLE
Devmode UnicodeDecodeError

### ISSUE THREAD

**Issue by RoyalSmirk** [junebug12851/Sims4ScriptingBPProj#5]
Heyhey,

OS: Windows 10
Python 3.7.9

I get this error while starting devmode.py and I dont know what's wrong.
![4444](https://user-images.githubusercontent.com/71403174/103453085-67049d00-4cd6-11eb-9517-98b891f37631.png)

Does it have to do with this?
![5555](https://user-images.githubusercontent.com/71403174/103453118-e3977b80-4cd6-11eb-8326-983ad7cae362.png)

**Comment by junebug12851** [comment]
This project has been abandoned and so has the tutorial series. I've updated the README about the reason why. I'm very sorry to give the bad news. I wish you the best of luck with this issue ^_^
