### ISSUE TITLE
Turn into Template Repository

### ISSUE THREAD

**Issue by polyjitter** [junebug12851/Sims4ScriptingBPProj#7]
In the settings for a repository, there is a toggle to list a repository as a "template". This lets others more easily use your repository to create a new project. I believe this would benefit those who wish to use this template.

**Comment by polyjitter** [comment]
![4BmkLBz 1](https://user-images.githubusercontent.com/18127936/118735310-297c5880-b80e-11eb-8cdd-079536642db5.png)

For clarity, this setting adds this button.

**Comment by junebug12851** [comment]
Done ^_^ thanks for letting me know. This project has been abandoned and so has the tutorial series. I've updated the README about the reason why. I'm very sorry to give the bad news.
